apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-shop-deployment
  namespace: sofa-shop-mysql
  labels:
    app: demo-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-shop
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: monitoring/sofa-shop-instrumentation-java	
      labels:
        app: demo-shop
    spec:
      nodeSelector:
       beta.kubernetes.io/arch: amd64
      containers:
      - name: demo-shop-app
        image: us-west1-docker.pkg.dev/zerok-dev/sofa-shop/frontend:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
