apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: us-west1-docker.pkg.dev/zerok-dev/java-spring-boot-demo/order:latest
          ports:
            - containerPort: 8080
