apiVersion: v1
kind: Service
metadata:
  name: availability
  labels:
    app: availability
spec:
  selector:
    app: availability
  type: ClusterIP # LoadBalancer # NodePort #
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 8080