{
 "title": "Sofa Shop Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sofa_shop_namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "namespace2",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "soakpod",
    "label": "Soak pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"zerok\"}, pod)"
    }
   },
   {
    "name": "spillpod",
    "label": "Spill pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"zerok\"}, pod)"
    }
   },
   { "name": "sofa_shop_inventory_traffic", "label": "Inventory Traffic", "query": "1m_5" },
   { "name": "time_unit", "label": "k6 Timeunit", "query": "1m" },
   { "name": "concurrencies", "query": "190_195_200_202_199_200" },
   { "name": "qos_app_traffic", "label": "QOS_app_traffic", "query": "2m_800-4m_1000-4m_1100" },
   { "name": "qos_zk_traffic", "label": "QOS_zk_traffic", "query": "2m_800-4m_1000_7:3-4m_1100_7:3" },
   { "name": "appcontainer", "label": "appcontainer", "query": "myapp" },
   { "name": "k6_app_url", "label": "k6-url", "query": "k6.sandbix01.getanton.com" },
   { "name": "sofa_shop_product_traffic", "label": "Product Traffic", "query": "1m_5" },
   { "name": "sofa_shop_order_traffic", "label": "Order Traffic", "query": "1m_5" }
  ]
 },
 "panels": [
  { "title": "Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "K6 Options - Start",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "\n\n<br>\n  <a \n     href=\"http://${k6_app_url}/start/sofa-shop-inventory?vus=5&mvus=5&timeunit=${time_unit}&stages=${sofa_shop_inventory_traffic}&rate=5&k6ScriptFilePath=/usr/src/app/k6script-inventory.js\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"inventory\">\n  ▶️ Inventory</a>\n   <a \n     href=\"http://${k6_app_url}/start/sofa-shop-product?vus=5&mvus=5&timeunit=${time_unit}&stages=${sofa_shop_product_traffic}&rate=5&k6ScriptFilePath=/usr/src/app/k6script-product.js\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"product\">\n  ▶️ Product</a>\n   <a \n     href=\"http://${k6_app_url}/start/sofa-shop-order?vus=5&mvus=5&timeunit=${time_unit}&stages=${sofa_shop_order_traffic}&rate=5&k6ScriptFilePath=/usr/src/app/k6script-order.js\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"order\">\n  ▶️ Order</a>\n\n  <a\n   href=\"http://${k6_app_url}/start-concurrent-tests?vus=300&mvus=300&timeunit=${time_unit}&sapp=${app_traffic}&ssoak=${soak_traffic}&sspill=${spill_traffic}&concurrency=${concurrencies}\"\n   target=\"_blank\"\n   style=\"\n      border-radius: 7px; \n      margin: 0.25rem; \n      border: 1px solid;\n      text-decoration: none; \n      cursor: pointer;\n      padding: 1rem 1.5rem; \n      width: 100px;\n      line-height: 10px;\n      font-size: 36px;\n      text-align: center;\"\n   >\n▶️ Concurrent\n</a>\n  \n<!--\n<a \nhref=\"https://aax7mshw45.execute-api.us-east-2.amazonaws.com/default/shutdown\"  \ntarget=\"_blank\"\nstyle=\"\nborder-radius: 7px; \nmargin: 0.25rem 0.30rem; \nborder: 1px solid;\ntext-decoration: none; \npadding: 1rem 1.5rem; \nwidth: 100px;\nline-height: 100px;\nfont-size: 36px;\ntext-align: center\"\ntitle=\"Kill demo machines\">\n🔥</a>\n-->"
   }
  },
  {
   "title": "K6 Options - Status and Reset",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "\n\n<br>\n  <a \n     href=\"http://${k6_app_url}/status/sofa-shop-inventory\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"inventory\">\n  🪵 Inventory</a>\n  <a \n     href=\"http://${k6_app_url}/status/sofa-shop-product\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"product\">\n  🪵 Product</a>\n  <a \n     href=\"http://${k6_app_url}/status/sofa-shop-order\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"order\">\n  🪵 Order</a>\n  <a \n     href=\"http://${k6_app_url}/reset\"\n     target=\"_blank\"\n     style=\"\n            border-radius: 7px; \n            margin: 0.25rem 0.30rem; \n            border: 1px solid;\n            text-decoration: none; \n            padding: 1rem 1.5rem; \n            width: 100px;\n            line-height: 100px;\n            font-size: 36px;\n            text-align: center\"\n     title=\"Reset the state\">\n  🔂</a>\n<!--\n<a \nhref=\"https://aax7mshw45.execute-api.us-east-2.amazonaws.com/default/shutdown\"  \ntarget=\"_blank\"\nstyle=\"\nborder-radius: 7px; \nmargin: 0.25rem 0.30rem; \nborder: 1px solid;\ntext-decoration: none; \npadding: 1rem 1.5rem; \nwidth: 100px;\nline-height: 100px;\nfont-size: 36px;\ntext-align: center\"\ntitle=\"Kill demo machines\">\n🔥</a>\n-->"
   }
  },
  { "title": "Stage 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "options": {
    "content": "# Concurrency Test\n\nGoal: \nObtain max concurrency value for a pod within the resource quotas keeping the latency impact to minimal. \n---"
   }
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(pod) (kube_pod_labels{namespace=\"sofa-shop\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(pod) (kube_pod_labels{namespace=\"sofa-shop\",pod=~\"inventory-.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(pod) (kube_pod_labels{namespace=\"sofa-shop\",pod=~\"order-.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count [zerok-soak/spill] -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(delta(k6_http_reqs{scenario=~\"zk_spill.*\"}[$__interval])) / 8",
     "legendFormat": "zk_spill"
    },
    {
     "expr": "sum(delta(k6_http_reqs{scenario=~\"zk_soak.*\"}[$__interval])) / 8",
     "legendFormat": "zk_soak"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(pod) (kube_pod_labels{namespace=\"myapp\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count - per pod - per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(delta(k6_http_reqs{scenario=~\"sofa-shop_.*\"}[$__interval]))",
     "legendFormat": "app"
    }
   ]
  },
  {
   "title": "Latency - $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(k6_custom_duration_avg{scenario=~\"sofa-shop_.*\"})",
     "legendFormat": "spill - {{scenario}}"
    },
    {
     "expr": "(k6_custom_duration_avg{scenario=~\"zk_soak_.*\"})",
     "legendFormat": "soak - {{scenario}}"
    }
   ]
  },
  {
   "title": "Latency - $sofa_shop_namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(k6_custom_duration_avg{scenario=~\"sofa-shop_.*\"})",
     "legendFormat": "sofa-shop-inventory"
    }
   ]
  },
  {
   "title": "Max concurrent request count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(k6_concurrency{scenario=~\"zk.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max concurrent request count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "NODATA", "legendFormat": "NODATA" }
   ]
  },
  {
   "title": "CPU Usage : $namespace2: soak pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"cpu\", pod=\"$soakpod\", container=\"$appcontainer\"}) * 1000\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace2\",pod=\"$soakpod\", container=\"$appcontainer\"}) by (namespace) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"cpu\",  pod=\"$soakpod\", container=\"myapp\"}) * 1000\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "CPU Usage : $sofa_shop_namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$sofa_shop_namespace\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$sofa_shop_namespace\"}) by (namespace) * 1000",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$sofa_shop_namespace\", resource=\"cpu\"}) * 1000\n",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "Error count [zerok-soak] -per min",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum by(scenario) (rate(k6_http_reqs{scenario=~\"zk_.*\", status!=\"200\"}[$__rate_interval]))",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Error count [sofa-shop] -per min",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by(scenario) (rate(k6_http_reqs{scenario=~\"sofa-shop_.*\", status!=\"200\"}[$__rate_interval]))",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  { "title": "Stage 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 50 }, "options": { "content": "# Quality Of service\n\n---" } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 50 },
   "options": {
    "content": "<br/>\n<a\n   href=\"http://demo-load-generator.getanton.com/start-concurrent-tests?vus=300&mvus=300&timeunit=${time_unit}&sapp=${qos_app_traffic}&szk=${qos_zk_traffic}\"\n   target=\"_blank\"\n   style=\"\n      border-radius: 7px; \n      margin: 0.25rem; \n      border: 1px solid;\n      text-decoration: none; \n      cursor: pointer;\n      padding: 1rem 1.5rem; \n      width: 100px;\n      line-height: 10px;\n      font-size: 36px;\n      text-align: center;\"\n   >\n▶️\n</a>\n"
   }
  },
  {
   "title": "Request count -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum (delta(k6_http_reqs{scenario=~\"app_.*\"}[$__interval])) / 8",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum by(status) (delta(k6_http_reqs{scenario=~\"app_.*\"}[$__interval])) / 8",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Request count [zerok] -per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum (delta(k6_http_reqs{scenario=~\"zk_.*\"}[$__interval])) / 8",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum by(status) (delta(k6_http_reqs{scenario=~\"zk_.*\"}[$__interval])) / 8",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Latency - $sofa_shop_namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(k6_custom_duration_avg{scenario=~\"app_.*\"})",
     "legendFormat": "app"
    }
   ]
  },
  {
   "title": "Latency - $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(k6_custom_duration_avg{scenario=~\"zk_.*\"})",
     "legendFormat": "app"
    }
   ]
  },
  {
   "title": "Error count [app] -per min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum (k6_http_reqs{scenario=~\"app_.*\"}) / 8",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum by(status) (k6_http_reqs{scenario=~\"app_.*\"}) / 8",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error count [zk] -per min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum (k6_http_reqs{scenario=~\"zk_.*\", status!=\"503\"}) / 8",
     "legendFormat": "Total requests"
    },
    {
     "expr": "(sum by(status) (k6_http_reqs{scenario=~\"zk_.*\", status=\"200\"}) / 8) + 200",
     "legendFormat": "{{scenario}}"
    },
    {
     "expr": "sum by(status) (k6_http_reqs{scenario=~\"zk_.*\", status=\"429\"}) / 8",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  { "title": "CPU charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "CPU Usage per Pod (limit) - $sofa_shop_namespace",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$sofa_shop_namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$sofa_shop_namespace\"}) by (pod)) * 100  ",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "CPU Usage per Pod (limit) - $sofa_shop_namespace",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace2\", pod!=\"$soakpod\", pod!=\"$spillpod\"}) * 100) / sum by(pod) (cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace2\", pod!=\"$soakpod\", pod!=\"$spillpod\"})",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "CPU Usage per Pod (limit) - $namespace2 - soak",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace2\", pod=\"$soakpod\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace2\", pod=\"$soakpod\"}) by (pod)) * 100  ",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "CPU Usage per Pod - $namespace2 - spill",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace2\", pod=\"$spillpod\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{ namespace=\"$namespace2\", pod=\"$spillpod\"}) by (pod)) * 100  ",
     "legendFormat": "  "
    }
   ]
  },
  { "title": "Memory charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Memory Usage per Pod - $sofa_shop_namespace",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$sofa_shop_namespace\", container!=\"\", image!=\"\"} / 1000000) by (pod)",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "Memory Usage per Pod - $namespace2",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\", container!=\"\", image!=\"\"} / 1000000) by (pod)",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "Memory Utilization - $sofa_shop_namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$sofa_shop_namespace\", container!=\"POD\", image!=\"\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$sofa_shop_namespace\", resource=\"memory\"}\n)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$sofa_shop_namespace\", resource=\"memory\"}\n)\n",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Utilization - $namespace2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace2\", container!=\"POD\", image!=\"\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"memory\"}\n)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace2\", resource=\"memory\"}\n)\n",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}