apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-shop-deployment
  labels:
    app: demo-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-shop
  template:
    metadata:
      labels:
        app: demo-shop
    spec:
      containers:
      - name: demo-shop-app
        image: us-west1-docker.pkg.dev/zerok-dev/sofa-shop/frontend:${EXTERNAL_HOSTNAME}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
