apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: us-west1-docker.pkg.dev/zerok-dev/java-spring-boot-demo/product:latest
          ports:
            - containerPort: 8080
