apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-shop-deployment
  namespace: sofa-shop-mysql
  labels:
    app: demo-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-shop
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: monitoring/sofa-shop-instrumentation-java	
      labels:
        app: demo-shop
    spec:
      nodeSelector:
       kubernetes.io/arch: amd64
      containers:
      - name: demo-shop-app
        image: us-west1-docker.pkg.dev/zerok-dev/sofa-shop/frontend:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: sofa-shop-mysql
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
      annotations:
        instrumentation.opentelemetry.io/inject-java: monitoring/sofa-shop-instrumentation-java
    spec:
      nodeSelector:
       kubernetes.io/arch: amd64
      containers:
        - name: order
          image: us-west1-docker.pkg.dev/zerok-dev/sofa-shop/order:configurable
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_URL_PARAMS   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: db_url_params

            - name: DB_DRIVER_TYPE   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: db_driver_type

            - name: DB_HIBERNATE_DIALECT   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: db_hibernate_dialect

            - name: DB_PRINT_SQL   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: db_print_sql

            - name: DB_DRIVER_CLASS   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: db_driver_class
                  
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: host

            - name: DB_NAME  # Setting PRODUCT Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: order-db-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: order-db-secrets
                  key: password

            - name: PRODUCT_HOST  # Setting PRODUCT service url from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: productServiceURL

            - name: INVENTORY_HOST  # Setting INVENTORY service url from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: inventoryServiceURL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: sofa-shop-mysql
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
      annotations:
        instrumentation.opentelemetry.io/inject-java: monitoring/sofa-shop-instrumentation-java
    spec:
      nodeSelector:
       kubernetes.io/arch: amd64
      containers:
        - name: product
          image: us-west1-docker.pkg.dev/zerok-dev/sofa-shop/product:configurable
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_URL_PARAMS   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_url_params

            - name: DB_DRIVER_TYPE   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_driver_type

            - name: DB_HIBERNATE_DIALECT   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_hibernate_dialect

            - name: DB_PRINT_SQL   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_print_sql

            - name: DB_DRIVER_CLASS   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_driver_class

            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: product-app-configmap
                  key: host

            - name: DB_NAME  # Setting PRODUCT Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: product-app-configmap
                  key: dbName

            - name: AVAILABILITY_HOST  # Setting AVAILABILITY service url from configMap
              valueFrom:
                configMapKeyRef:
                  name: product-app-configmap
                  key: availabilityServiceURL

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: product-db-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: product-db-secrets
                  key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: sofa-shop-mysql
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
      group: zerok-demoapp
  template:
    metadata:
      labels:
        app: inventory
        group: zerok-demoapp
      annotations:
        instrumentation.opentelemetry.io/inject-java: monitoring/sofa-shop-instrumentation-java
    spec:
      nodeSelector:
       kubernetes.io/arch: amd64
      containers:
        - name: inventory
          image: us-west1-docker.pkg.dev/zerok-dev/sofa-shop/inventory:configurable
          imagePullPolicy: Always
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 0
#            periodSeconds: 1
          resources:
            limits:
              cpu: "0.3"
              memory: "1512Mi"
            requests:
              cpu: "0.2"
              memory: "1000Mi"
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_URL_PARAMS   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_url_params

            - name: DB_DRIVER_TYPE   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_driver_type

            - name: DB_HIBERNATE_DIALECT   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_hibernate_dialect

            - name: DB_PRINT_SQL   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_print_sql

            - name: DB_DRIVER_CLASS   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_driver_class

            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: host

            - name: DB_NAME  # Setting INVENTORY Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: dbName

            - name: PRODUCT_HOST  # Setting PRODUCT service url from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: productServiceURL

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secrets
                  key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: sofa-shop-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: sofa-shop-mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: initdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadrun-deployment
  namespace: sofa-shop-mysql
  labels:
    app: loadrun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadrun
  template:
    metadata:
      labels:
        app: loadrun
    spec:
      containers:
      - name: curl
        image:  alpine/curl
        command: [ "sh", "-c", "--" ]
        args: [ "while true; do sleep 30; curl -ss -H 'traceparent: 00-aaaaaaaa'$(tr -dc 'a-f0-9' < /dev/urandom | head -c24)'-'$(tr -dc 'a-f0-9' < /dev/urandom | head -c16)'-01' -w '\n%{http_code} ' http://inventory.sofa-shop-mysql.svc.cluster.local/api/inventory/all; done;" ]
        resources: 
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 40Mi