apiVersion : v1
kind : Secret
metadata:
  name : inventory-db-secrets
  namespace: sofa-shop-mysql
data:
  username : c2VydmljZV91c2Vy
  password : cGFzc3RmOQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: sofa-shop-mysql
type: kubernetes.io/basic-auth
stringData:
  password: test1234
---
apiVersion : v1
kind : Secret
metadata:
  name : order-db-secrets
  namespace: sofa-shop-mysql
data:
  username : c2VydmljZV91c2Vy
  password : cGFzc3RmOQ==
---
apiVersion : v1
kind : Secret
metadata:
  name : product-db-secrets
  namespace: sofa-shop-mysql
data:
  username : c2VydmljZV91c2Vy
  password : cGFzc3RmOQ==
