apiVersion: v1
kind: Service
metadata:
  name: demo-shop-service
  namespace: sofa-shop-mysql
spec:
  selector:
    app: demo-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: sofa-shop-mysql
  labels:
    app: inventory
spec:
  selector:
    app: inventory
  type: ClusterIP # LoadBalancer # NodePort #
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: sofa-shop-mysql
  labels:
    app: order
spec:
  selector:
    app: order
  type: ClusterIP
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: sofa-shop-mysql
  labels:
    app: product
spec:
  selector:
    app: product
  type: ClusterIP
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 8080