apiVersion: v1
data:
  db_url_params: "?createDatabaseIfNotExist=true"
  db_driver_type: mysql
  db_hibernate_dialect: org.hibernate.dialect.MySQL5Dialect
  db_print_sql: "false"
  db_driver_class: com.mysql.cj.jdbc.Driver
  host: mysql.mysql.svc.cluster.local:3306
  dbName: orderservice
  productServiceURL: product.sofa-shop-mysql.svc.cluster.local
  inventoryServiceURL: inventory.sofa-shop-mysql.svc.cluster.local
kind: ConfigMap
metadata:
  name: order-app-configmap