apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: us-west1-docker.pkg.dev/zerok-dev/java-spring-boot-demo/order:postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: host

            - name: DB_NAME  # Setting PRODUCT Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: order-mysql-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: order-mysql-secrets
                  key: password

            - name: PRODUCT_HOST  # Setting PRODUCT service url from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: productServiceURL

            - name: INVENTORY_HOST  # Setting INVENTORY service url from configMap
              valueFrom:
                configMapKeyRef:
                  name: order-app-configmap
                  key: inventoryServiceURL

