apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: sofa-shop-mysql
  labels:
    app: order
spec:
  selector:
    app: order
  type: ClusterIP # LoadBalancer # NodePort #
  ports:
    - protocol: TCP
      name: m-http
      port: 80
      targetPort: 8080