apiVersion: v1
data:
  db_url_params: ""
  db_driver_type: postgresql
  db_hibernate_dialect: org.hibernate.dialect.PostgreSQLDialect
  db_print_sql: "false"
  db_driver_class: org.postgresql.Driver
  host: postgres-postgresql.postgres.svc.cluster.local:5432
  dbName: inventoryservice
  productServiceURL: product.sofa-shop-ps.svc.cluster.local
kind: ConfigMap
metadata:
  name: inventory-app-configmap