apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: us-west1-docker.pkg.dev/zerok-dev/java-spring-boot-demo/inventory:latest
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: host

            - name: DB_NAME  # Setting INVENTORY Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: dbName

            - name: PRODUCT_HOST  # Setting PRODUCT service url from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: productServiceURL

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: inventory-mysql-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: inventory-mysql-secrets
                  key: password

