apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
      group: zerok-demoapp
  template:
    metadata:
      labels:
        app: inventory
        group: zerok-demoapp
    spec:
      nodeSelector:
       beta.kubernetes.io/arch: amd64
      containers:
        - name: inventory
          image: us-west1-docker.pkg.dev/zerok-dev/sofa-shop/inventory:configurable
          imagePullPolicy: Always
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 0
#            periodSeconds: 1
          resources:
            limits:
              cpu: "0.3"
              memory: "1512Mi"
            requests:
              cpu: "0.2"
              memory: "1000Mi"
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_URL_PARAMS   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_url_params

            - name: DB_DRIVER_TYPE   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_driver_type

            - name: DB_HIBERNATE_DIALECT   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_hibernate_dialect

            - name: DB_PRINT_SQL   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_print_sql

            - name: DB_DRIVER_CLASS   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: db_driver_class

            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: host

            - name: DB_NAME  # Setting INVENTORY Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: dbName

            - name: PRODUCT_HOST  # Setting PRODUCT service url from configMap
              valueFrom:
                configMapKeyRef:
                  name: inventory-app-configmap
                  key: productServiceURL

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secrets
                  key: password

